//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remwave.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remwave.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap attach {
            get {
                object obj = ResourceManager.GetObject("attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backgroundMenu {
            get {
                object obj = ResourceManager.GetObject("backgroundMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonContacts {
            get {
                object obj = ResourceManager.GetObject("buttonContacts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonContactsOn {
            get {
                object obj = ResourceManager.GetObject("buttonContactsOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonContactsOver {
            get {
                object obj = ResourceManager.GetObject("buttonContactsOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonIconContacts {
            get {
                object obj = ResourceManager.GetObject("buttonIconContacts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonOff {
            get {
                object obj = ResourceManager.GetObject("ButtonOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonOn {
            get {
                object obj = ResourceManager.GetObject("ButtonOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonOnline {
            get {
                object obj = ResourceManager.GetObject("buttonOnline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonOnlineOn {
            get {
                object obj = ResourceManager.GetObject("buttonOnlineOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonOnlineOver {
            get {
                object obj = ResourceManager.GetObject("buttonOnlineOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonPhone {
            get {
                object obj = ResourceManager.GetObject("buttonPhone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonPhoneOn {
            get {
                object obj = ResourceManager.GetObject("buttonPhoneOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonPhoneOver {
            get {
                object obj = ResourceManager.GetObject("buttonPhoneOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CallDialed {
            get {
                object obj = ResourceManager.GetObject("CallDialed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CallMissed {
            get {
                object obj = ResourceManager.GetObject("CallMissed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CallReceived {
            get {
                object obj = ResourceManager.GetObject("CallReceived", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contactAdd {
            get {
                object obj = ResourceManager.GetObject("contactAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ContactBlank {
            get {
                object obj = ResourceManager.GetObject("ContactBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialPadButton {
            get {
                object obj = ResourceManager.GetObject("dialPadButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialPadButtonOn {
            get {
                object obj = ResourceManager.GetObject("dialPadButtonOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialPadButtonOver {
            get {
                object obj = ResourceManager.GetObject("dialPadButtonOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialPadFuncButton {
            get {
                object obj = ResourceManager.GetObject("dialPadFuncButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dialPadFuncButton1 {
            get {
                object obj = ResourceManager.GetObject("dialPadFuncButton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonEvilgrin {
            get {
                object obj = ResourceManager.GetObject("emoticonEvilgrin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonGrin {
            get {
                object obj = ResourceManager.GetObject("emoticonGrin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonHappy {
            get {
                object obj = ResourceManager.GetObject("emoticonHappy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonSmile {
            get {
                object obj = ResourceManager.GetObject("emoticonSmile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonSurprised {
            get {
                object obj = ResourceManager.GetObject("emoticonSurprised", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonTongue {
            get {
                object obj = ResourceManager.GetObject("emoticonTongue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonUnhappy {
            get {
                object obj = ResourceManager.GetObject("emoticonUnhappy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonWaii {
            get {
                object obj = ResourceManager.GetObject("emoticonWaii", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap emoticonWink {
            get {
                object obj = ResourceManager.GetObject("emoticonWink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****************** GENERATORS ********************/CREATE GENERATOR MESSAGEIDGEN;
        ///CREATE GENERATOR USERIDGEN;
        ///
        ////******************** DOMAINS *********************/
        ///CREATE DOMAIN MESSAGEID
        /// AS Integer
        /// CHECK (VALUE &gt; 0)
        ///;
        ///CREATE DOMAIN MSG_DIRECTION
        /// AS Varchar(8) CHARACTER SET UTF8
        /// DEFAULT &apos;NA&apos;
        /// NOT NULL
        /// CHECK (VALUE IN (&apos;IN&apos;, &apos;OUT&apos;, &apos;NA&apos;))
        /// COLLATE UTF8;
        ///CREATE DOMAIN USERID
        /// AS Integer
        /// CHECK (VALUE &gt; 0)
        ///;
        ///
        ////******************* PROCEDURES ******************/
        ///SET TERM ^ ;
        ///CREATE PRO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fbDDL_1_0_0 {
            get {
                return ResourceManager.GetString("fbDDL_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET TERM ^ ;
        ///ALTER PROCEDURE MESSAGE_FIND (
        ///    iUSER_ID Integer,
        ///    iUSERNAME Varchar(32) CHARACTER SET UTF8,
        ///    iSEARCH Varchar(32) CHARACTER SET UTF8,
        ///    iLIMIT Integer )
        ///RETURNS (
        ///    oUSERNAME Varchar(32) CHARACTER SET UTF8,
        ///    oCONTENT Varchar(4096) CHARACTER SET UTF8,
        ///    oDIRECTION Varchar(8) CHARACTER SET UTF8,
        ///    oCREATED Timestamp )
        ///AS
        ///BEGIN 
        ///
        ///FOR SELECT FIRST (:iLIMIT) USERNAME, CONTENT, DIRECTION, CREATED 
        ///FROM MESSAGES 
        ///WHERE LOWER(CONTENT) like LOWER(:iSEARCH) 
        ///AND USE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fbDDL_1_0_1 {
            get {
                return ResourceManager.GetString("fbDDL_1_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE MESSAGE_ADD;
        ///DROP PROCEDURE MESSAGE_FIND;
        ///
        ///ALTER TABLE MESSAGES ADD CONTENT_HTML Varchar(6144) CHARACTER SET UTF8 COLLATE UTF8;
        ///ALTER TABLE MESSAGES ALTER CONTENT TO CONTENT_TEXT;
        ///
        ///UPDATE MESSAGES SET CONTENT_HTML = CONTENT_TEXT;
        ///UPDATE MESSAGES SET CONTENT_HTML = CONTENT_TEXT;
        ///
        ///SET TERM ^ ;
        ///CREATE PROCEDURE MESSAGE_ADD (
        ///    iUSER_ID Integer,
        ///    iGUID Varchar(128) CHARACTER SET UTF8,
        ///    iUSERNAME Varchar(32) CHARACTER SET UTF8,
        ///    iCONTENT_TEXT Varchar(4096) CHARACTER SET UT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fbDDL_1_0_2 {
            get {
                return ResourceManager.GetString("fbDDL_1_0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE MESSAGES SET JID = LOWER(JID);
        ///
        ///SET TERM ^ ;
        ///ALTER PROCEDURE MESSAGE_FIND (
        ///    iUSER_ID Integer,
        ///    iJID Varchar(64) CHARACTER SET UTF8,
        ///    iSEARCH Varchar(64) CHARACTER SET UTF8,
        ///    iLIMIT Integer )
        ///RETURNS (
        ///    oJID Varchar(64) CHARACTER SET UTF8,
        ///	oCONTENT_TEXT Varchar(4096) CHARACTER SET UTF8,
        ///    oCONTENT_HTML Varchar(6144) CHARACTER SET UTF8,
        ///    oDIRECTION Varchar(8) CHARACTER SET UTF8,
        ///    oCREATED Timestamp )
        ///AS
        ///BEGIN 
        ///
        ///FOR SELECT FIRST (:iLIMIT) JID, CONTENT_TEXT, CONT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fbDDL_1_0_3 {
            get {
                return ResourceManager.GetString("fbDDL_1_0_3", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap iconArchive {
            get {
                object obj = ResourceManager.GetObject("iconArchive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconColorSwatch {
            get {
                object obj = ResourceManager.GetObject("iconColorSwatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconCross {
            get {
                object obj = ResourceManager.GetObject("iconCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconFont {
            get {
                object obj = ResourceManager.GetObject("iconFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconMagnifier {
            get {
                object obj = ResourceManager.GetObject("iconMagnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconMessage {
            get {
                object obj = ResourceManager.GetObject("iconMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconNudge {
            get {
                object obj = ResourceManager.GetObject("iconNudge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconPhoneAnswer {
            get {
                object obj = ResourceManager.GetObject("iconPhoneAnswer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconPhoneHangup {
            get {
                object obj = ResourceManager.GetObject("iconPhoneHangup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconRefresh {
            get {
                object obj = ResourceManager.GetObject("iconRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_aim {
            get {
                object obj = ResourceManager.GetObject("im_aim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_aim_offline {
            get {
                object obj = ResourceManager.GetObject("im_aim_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_gadugadu {
            get {
                object obj = ResourceManager.GetObject("im_gadugadu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_gadugadu_offline {
            get {
                object obj = ResourceManager.GetObject("im_gadugadu_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_icq {
            get {
                object obj = ResourceManager.GetObject("im_icq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_icq_offline {
            get {
                object obj = ResourceManager.GetObject("im_icq_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_irc {
            get {
                object obj = ResourceManager.GetObject("im_irc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_irc_offline {
            get {
                object obj = ResourceManager.GetObject("im_irc_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_msn {
            get {
                object obj = ResourceManager.GetObject("im_msn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_msn_offline {
            get {
                object obj = ResourceManager.GetObject("im_msn_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_yahoo {
            get {
                object obj = ResourceManager.GetObject("im_yahoo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap im_yahoo_offline {
            get {
                object obj = ResourceManager.GetObject("im_yahoo_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconComputer {
            get {
                object obj = ResourceManager.GetObject("listIconComputer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconEmail {
            get {
                object obj = ResourceManager.GetObject("listIconEmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconInstantMessage {
            get {
                object obj = ResourceManager.GetObject("listIconInstantMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconNotFound {
            get {
                object obj = ResourceManager.GetObject("listIconNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconPhone {
            get {
                object obj = ResourceManager.GetObject("listIconPhone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconScreenSharing {
            get {
                object obj = ResourceManager.GetObject("listIconScreenSharing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconVcard {
            get {
                object obj = ResourceManager.GetObject("listIconVcard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconVcardAdd {
            get {
                object obj = ResourceManager.GetObject("listIconVcardAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap listIconWebcam {
            get {
                object obj = ResourceManager.GetObject("listIconWebcam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap menuBackground {
            get {
                object obj = ResourceManager.GetObject("menuBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonCancel {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonCancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonCancelDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonCancelDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonCancelOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonCancelOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonDelete {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonDeleteDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonDeleteDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonDeleteOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonDeleteOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonDone {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonDoneDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonDoneDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonDoneOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonDoneOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonPlay {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonPlayDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonPlayDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonPlayOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonPlayOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonReply {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonReply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonReplyDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonReplyDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonReplyOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonReplyOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonReview {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonReview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonReviewDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonReviewDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonReviewOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonReviewOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonSend {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonSend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonSendDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonSendDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonSendOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonSendOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonStop {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonStop1 {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonStop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonStopDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonStopDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonStopDown1 {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonStopDown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonStopOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonStopOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonStopOver1 {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonStopOver1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonTalk {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonTalk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonTalk1 {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonTalk1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonTalkDown {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonTalkDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonTalkDown1 {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonTalkDown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonTalkOver {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonTalkOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieButtonTalkOver1 {
            get {
                object obj = ResourceManager.GetObject("NikotalkieButtonTalkOver1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieControlBackground {
            get {
                object obj = ResourceManager.GetObject("NikotalkieControlBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieIconMessage20 {
            get {
                object obj = ResourceManager.GetObject("NikotalkieIconMessage20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieItemBackgroundBlack {
            get {
                object obj = ResourceManager.GetObject("NikotalkieItemBackgroundBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieItemBackgroundBlackSelected {
            get {
                object obj = ResourceManager.GetObject("NikotalkieItemBackgroundBlackSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieItemBackgroundWhite {
            get {
                object obj = ResourceManager.GetObject("NikotalkieItemBackgroundWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NikotalkieRecordingIcon {
            get {
                object obj = ResourceManager.GetObject("NikotalkieRecordingIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num0 {
            get {
                object obj = ResourceManager.GetObject("Num0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num1 {
            get {
                object obj = ResourceManager.GetObject("Num1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num2 {
            get {
                object obj = ResourceManager.GetObject("Num2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num3 {
            get {
                object obj = ResourceManager.GetObject("Num3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num4 {
            get {
                object obj = ResourceManager.GetObject("Num4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num5 {
            get {
                object obj = ResourceManager.GetObject("Num5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num6 {
            get {
                object obj = ResourceManager.GetObject("Num6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num7 {
            get {
                object obj = ResourceManager.GetObject("Num7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num8 {
            get {
                object obj = ResourceManager.GetObject("Num8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num9 {
            get {
                object obj = ResourceManager.GetObject("Num9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NumAst {
            get {
                object obj = ResourceManager.GetObject("NumAst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NumPound {
            get {
                object obj = ResourceManager.GetObject("NumPound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone2phone {
            get {
                object obj = ResourceManager.GetObject("phone2phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhoneAnswer {
            get {
                object obj = ResourceManager.GetObject("PhoneAnswer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhoneAnswerOn {
            get {
                object obj = ResourceManager.GetObject("PhoneAnswerOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PhoneHangUp {
            get {
                object obj = ResourceManager.GetObject("PhoneHangUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splashImage {
            get {
                object obj = ResourceManager.GetObject("splashImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userAway {
            get {
                object obj = ResourceManager.GetObject("userAway", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userDND {
            get {
                object obj = ResourceManager.GetObject("userDND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userExtendedAway {
            get {
                object obj = ResourceManager.GetObject("userExtendedAway", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userOffline {
            get {
                object obj = ResourceManager.GetObject("userOffline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap userOnline {
            get {
                object obj = ResourceManager.GetObject("userOnline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vcard_add {
            get {
                object obj = ResourceManager.GetObject("vcard_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webcam {
            get {
                object obj = ResourceManager.GetObject("webcam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
