ALTER TABLE MESSAGES ADD "DAY" Date;

alter table MESSAGES
add constraint PK_MESSAGES_1
primary key (MESSAGE_ID);


alter table USERS
add constraint PK_USERS_1
primary key (USER_ID);

CREATE INDEX IDX_USERS_1 ON USERS
  (USERNAME);

CREATE INDEX IDX_MESSAGES_1 ON MESSAGES
  (USER_ID, JID);
  
CREATE INDEX IDX_MESSAGES_2 ON MESSAGES
  ("DAY");

UPDATE MESSAGES SET "DAY" = CAST (CREATED AS DATE);

SET TERM ^ ;
ALTER PROCEDURE MESSAGE_ARCHIVE_USERS (
    iUSER_ID Integer
)
RETURNS (
    oJID Varchar(64) CHARACTER SET UTF8,
    oDIRECTION Varchar(8) CHARACTER SET UTF8,
    oCREATED Timestamp )
AS
BEGIN 
FOR SELECT JID, MAX(DIRECTION) DIRECTION,  MAX(CREATED) CREATED
FROM MESSAGES
WHERE USER_ID =  :iUSER_ID 
GROUP BY JID
ORDER BY JID ASC 
INTO :oJID, :oDIRECTION , :oCREATED DO
  BEGIN
   SUSPEND;
  END
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_ARCHIVE_USERS TO  SYSDBA;
  
SET TERM ^ ;
ALTER PROCEDURE MESSAGE_ADD (
    iUSER_ID Integer,
    iGUID Varchar(128) CHARACTER SET UTF8,
    iJID Varchar(64) CHARACTER SET UTF8,
    iCONTENT_TEXT Varchar(4096) CHARACTER SET UTF8,
	iCONTENT_HTML Varchar(6144) CHARACTER SET UTF8,
    iDIRECTION Varchar(8) )
AS
BEGIN 
 BEGIN 
 INSERT INTO MESSAGES (USER_ID, GUID,JID,CONTENT_TEXT, CONTENT_HTML, DIRECTION, CREATED, "DAY") VALUES (:iUSER_ID, :iGUID, LOWER(:iJID), :iCONTENT_TEXT, :iCONTENT_HTML, :iDIRECTION, 'NOW', CAST ('NOW' AS DATE)); 
 END 
 SUSPEND; 
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_ADD TO  SYSDBA;



SET TERM ^ ;
ALTER PROCEDURE MESSAGE_FIND_BY_DATE (
    iUSER_ID Integer,
    iJID Varchar(64) CHARACTER SET UTF8,
    iSEARCH Varchar(64) CHARACTER SET UTF8,
    iLIMIT Integer,
iDATE Date	)
RETURNS (
    oJID Varchar(64) CHARACTER SET UTF8,
	oCONTENT_TEXT Varchar(4096) CHARACTER SET UTF8,
    oCONTENT_HTML Varchar(6144) CHARACTER SET UTF8,
    oDIRECTION Varchar(8) CHARACTER SET UTF8,
    oCREATED Timestamp )
AS
BEGIN 

FOR SELECT FIRST (:iLIMIT) JID, CONTENT_TEXT, CONTENT_HTML, DIRECTION, CREATED 
FROM MESSAGES 
WHERE LOWER(CONTENT_TEXT) like LOWER(:iSEARCH) 
AND JID = LOWER(:iJID)
AND USER_ID =  :iUSER_ID
AND  "DAY"  = :iDATE
ORDER BY CREATED DESC 
INTO :oJID, :oCONTENT_TEXT,oCONTENT_HTML, :oDIRECTION , :oCREATED DO
  BEGIN
   SUSPEND;
  END
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_FIND_BY_DATE TO  SYSDBA;
 
 

SET TERM ^ ;
ALTER PROCEDURE MESSAGE_DATES_FIND (
    iUSER_ID Integer,
    iJID Varchar(64) CHARACTER SET UTF8,
    iSEARCH Varchar(64) CHARACTER SET UTF8,
    iLIMIT Integer )
RETURNS (
    oDAY Date,
	oDATE Timestamp,
	oDAYS Integer)
AS
BEGIN 

FOR SELECT FIRST (:iLIMIT)  MAX(CREATED) DATE_, "DAY" DAY_,  CAST ('NOW' AS DATE) - "DAY"   DAYS_
FROM MESSAGES 
WHERE LOWER(CONTENT_TEXT) like LOWER(:iSEARCH) 
AND JID = LOWER(:iJID)
AND USER_ID =  :iUSER_ID 
GROUP by "DAY"
ORDER by DAY_ DESC
INTO :oDATE, :oDAY, :oDAYS DO
  BEGIN
   SUSPEND;
  END
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_DATES_FIND TO  SYSDBA;
 
 
 
SET TERM ^ ;
ALTER PROCEDURE OPENDB (
    iUSERNAME Varchar(64) CHARACTER SET UTF8 )
RETURNS (
    oUSER_ID Integer,
    oVERSION Varchar(32) CHARACTER SET UTF8 )
AS
DECLARE VARIABLE cnt INTEGER; 
BEGIN 
 SELECT count(USER_ID) FROM USERS WHERE USERNAME = :iUSERNAME INTO :cnt; 
 IF (cnt = 0) THEN 
  INSERT INTO USERS (USERNAME) VALUES (:iUSERNAME); 
 FOR SELECT USER_ID , '1.0.6'
  FROM USERS 
  WHERE USERNAME = :iUSERNAME 
  INTO :oUSER_ID , :oVERSION
  DO SUSPEND; 
END^
SET TERM ; ^
GRANT EXECUTE
 ON PROCEDURE OPENDB TO  SYSDBA;
