//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace Remwave.Client.MailService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://vmservice.remwave.com/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VoiceMail_GetMessageListOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoiceMail_GetMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoiceMail_DeleteMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoiceMail_ArchiveMessageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = "http://63.214.186.103/TerraMailWebService/Service.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VoiceMail_GetMessageListCompletedEventHandler VoiceMail_GetMessageListCompleted;
        
        /// <remarks/>
        public event VoiceMail_GetMessageCompletedEventHandler VoiceMail_GetMessageCompleted;
        
        /// <remarks/>
        public event VoiceMail_DeleteMessageCompletedEventHandler VoiceMail_DeleteMessageCompleted;
        
        /// <remarks/>
        public event VoiceMail_ArchiveMessageCompletedEventHandler VoiceMail_ArchiveMessageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vmservice.remwave.com/VoiceMail_GetMessageList", RequestNamespace="http://vmservice.remwave.com/", ResponseNamespace="http://vmservice.remwave.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileInfo[] VoiceMail_GetMessageList(string username, string password) {
            object[] results = this.Invoke("VoiceMail_GetMessageList", new object[] {
                        username,
                        password});
            return ((FileInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void VoiceMail_GetMessageListAsync(string username, string password) {
            this.VoiceMail_GetMessageListAsync(username, password, null);
        }
        
        /// <remarks/>
        public void VoiceMail_GetMessageListAsync(string username, string password, object userState) {
            if ((this.VoiceMail_GetMessageListOperationCompleted == null)) {
                this.VoiceMail_GetMessageListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoiceMail_GetMessageListOperationCompleted);
            }
            this.InvokeAsync("VoiceMail_GetMessageList", new object[] {
                        username,
                        password}, this.VoiceMail_GetMessageListOperationCompleted, userState);
        }
        
        private void OnVoiceMail_GetMessageListOperationCompleted(object arg) {
            if ((this.VoiceMail_GetMessageListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoiceMail_GetMessageListCompleted(this, new VoiceMail_GetMessageListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vmservice.remwave.com/VoiceMail_GetMessage", RequestNamespace="http://vmservice.remwave.com/", ResponseNamespace="http://vmservice.remwave.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageReturn VoiceMail_GetMessage(string username, string password, string messageid, LocationType type) {
            object[] results = this.Invoke("VoiceMail_GetMessage", new object[] {
                        username,
                        password,
                        messageid,
                        type});
            return ((MessageReturn)(results[0]));
        }
        
        /// <remarks/>
        public void VoiceMail_GetMessageAsync(string username, string password, string messageid, LocationType type) {
            this.VoiceMail_GetMessageAsync(username, password, messageid, type, null);
        }
        
        /// <remarks/>
        public void VoiceMail_GetMessageAsync(string username, string password, string messageid, LocationType type, object userState) {
            if ((this.VoiceMail_GetMessageOperationCompleted == null)) {
                this.VoiceMail_GetMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoiceMail_GetMessageOperationCompleted);
            }
            this.InvokeAsync("VoiceMail_GetMessage", new object[] {
                        username,
                        password,
                        messageid,
                        type}, this.VoiceMail_GetMessageOperationCompleted, userState);
        }
        
        private void OnVoiceMail_GetMessageOperationCompleted(object arg) {
            if ((this.VoiceMail_GetMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoiceMail_GetMessageCompleted(this, new VoiceMail_GetMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vmservice.remwave.com/VoiceMail_DeleteMessage", RequestNamespace="http://vmservice.remwave.com/", ResponseNamespace="http://vmservice.remwave.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnStatus VoiceMail_DeleteMessage(string username, string password, string messageid, LocationType type) {
            object[] results = this.Invoke("VoiceMail_DeleteMessage", new object[] {
                        username,
                        password,
                        messageid,
                        type});
            return ((ReturnStatus)(results[0]));
        }
        
        /// <remarks/>
        public void VoiceMail_DeleteMessageAsync(string username, string password, string messageid, LocationType type) {
            this.VoiceMail_DeleteMessageAsync(username, password, messageid, type, null);
        }
        
        /// <remarks/>
        public void VoiceMail_DeleteMessageAsync(string username, string password, string messageid, LocationType type, object userState) {
            if ((this.VoiceMail_DeleteMessageOperationCompleted == null)) {
                this.VoiceMail_DeleteMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoiceMail_DeleteMessageOperationCompleted);
            }
            this.InvokeAsync("VoiceMail_DeleteMessage", new object[] {
                        username,
                        password,
                        messageid,
                        type}, this.VoiceMail_DeleteMessageOperationCompleted, userState);
        }
        
        private void OnVoiceMail_DeleteMessageOperationCompleted(object arg) {
            if ((this.VoiceMail_DeleteMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoiceMail_DeleteMessageCompleted(this, new VoiceMail_DeleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://vmservice.remwave.com/VoiceMail_ArchiveMessage", RequestNamespace="http://vmservice.remwave.com/", ResponseNamespace="http://vmservice.remwave.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnStatus VoiceMail_ArchiveMessage(string username, string password, string messageid) {
            object[] results = this.Invoke("VoiceMail_ArchiveMessage", new object[] {
                        username,
                        password,
                        messageid});
            return ((ReturnStatus)(results[0]));
        }
        
        /// <remarks/>
        public void VoiceMail_ArchiveMessageAsync(string username, string password, string messageid) {
            this.VoiceMail_ArchiveMessageAsync(username, password, messageid, null);
        }
        
        /// <remarks/>
        public void VoiceMail_ArchiveMessageAsync(string username, string password, string messageid, object userState) {
            if ((this.VoiceMail_ArchiveMessageOperationCompleted == null)) {
                this.VoiceMail_ArchiveMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoiceMail_ArchiveMessageOperationCompleted);
            }
            this.InvokeAsync("VoiceMail_ArchiveMessage", new object[] {
                        username,
                        password,
                        messageid}, this.VoiceMail_ArchiveMessageOperationCompleted, userState);
        }
        
        private void OnVoiceMail_ArchiveMessageOperationCompleted(object arg) {
            if ((this.VoiceMail_ArchiveMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoiceMail_ArchiveMessageCompleted(this, new VoiceMail_ArchiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vmservice.remwave.com/")]
    public partial class FileInfo {
        
        private LocationType locationField;
        
        private string fileNameField;
        
        private long fileSizeField;
        
        private double timeField;
        
        private string dayField;
        
        private string monthField;
        
        private string yearField;
        
        private string fromField;
        
        private string tagsField;
        
        /// <remarks/>
        public LocationType Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public long FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        public double Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        public string Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vmservice.remwave.com/")]
    public enum LocationType {
        
        /// <remarks/>
        ARCHIVE,
        
        /// <remarks/>
        INBOX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vmservice.remwave.com/")]
    public partial class MessageReturn {
        
        private ReturnStatus errorField;
        
        private CompressionType compressedFormatField;
        
        private long actualFileSizeField;
        
        private long compressedFileSizeField;
        
        private byte[] bytesField;
        
        /// <remarks/>
        public ReturnStatus Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public CompressionType CompressedFormat {
            get {
                return this.compressedFormatField;
            }
            set {
                this.compressedFormatField = value;
            }
        }
        
        /// <remarks/>
        public long ActualFileSize {
            get {
                return this.actualFileSizeField;
            }
            set {
                this.actualFileSizeField = value;
            }
        }
        
        /// <remarks/>
        public long CompressedFileSize {
            get {
                return this.compressedFileSizeField;
            }
            set {
                this.compressedFileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Bytes {
            get {
                return this.bytesField;
            }
            set {
                this.bytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vmservice.remwave.com/")]
    public enum ReturnStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        FileNotFound,
        
        /// <remarks/>
        UserNamePasswordOrIdNull,
        
        /// <remarks/>
        UserNamePasswordOrIdTooLarge,
        
        /// <remarks/>
        UserNameInvalid,
        
        /// <remarks/>
        InavlidID,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        WaveFileNotDeleted,
        
        /// <remarks/>
        WaveInfoFileNotDeleted,
        
        /// <remarks/>
        WaveFileNotFound,
        
        /// <remarks/>
        WaveInfoFileNotFound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://vmservice.remwave.com/")]
    public enum CompressionType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Zip,
        
        /// <remarks/>
        BZip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void VoiceMail_GetMessageListCompletedEventHandler(object sender, VoiceMail_GetMessageListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoiceMail_GetMessageListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoiceMail_GetMessageListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void VoiceMail_GetMessageCompletedEventHandler(object sender, VoiceMail_GetMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoiceMail_GetMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoiceMail_GetMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void VoiceMail_DeleteMessageCompletedEventHandler(object sender, VoiceMail_DeleteMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoiceMail_DeleteMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoiceMail_DeleteMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void VoiceMail_ArchiveMessageCompletedEventHandler(object sender, VoiceMail_ArchiveMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoiceMail_ArchiveMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoiceMail_ArchiveMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnStatus)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591