
/******************* PROCEDURES ******************/
SET TERM ^ ;
CREATE PROCEDURE MESSAGE_DELETE_GUID (
    iUSER_ID Integer,
    iGUID Varchar(128) CHARACTER SET UTF8,
    iJID Varchar(64) CHARACTER SET UTF8 )
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE MESSAGE_DELETE_JID (
    iUSER_ID Integer,
    iJID Varchar(64) CHARACTER SET UTF8 )
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
ALTER PROCEDURE MESSAGE_DELETE_GUID (
    iUSER_ID Integer,
    iGUID Varchar(128) CHARACTER SET UTF8,
    iJID Varchar(64) CHARACTER SET UTF8 )
AS
BEGIN
BEGIN 
DELETE FROM MESSAGES WHERE USER_ID = :iUSER_ID AND GUID = :iGUID AND JID = LOWER(:iJID);
END
SUSPEND;
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_DELETE_GUID TO  SYSDBA;

SET TERM ^ ;
ALTER PROCEDURE MESSAGE_DELETE_JID (
    iUSER_ID Integer,
    iJID Varchar(64) CHARACTER SET UTF8 )
AS
BEGIN
BEGIN 
DELETE FROM MESSAGES WHERE USER_ID = :iUSER_ID AND JID = LOWER(:iJID);
END
SUSPEND;
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_DELETE_JID TO  SYSDBA;

SET TERM ^ ;
ALTER PROCEDURE OPENDB (
    iUSERNAME Varchar(64) CHARACTER SET UTF8 )
RETURNS (
    oUSER_ID Integer,
    oVERSION Varchar(32) CHARACTER SET UTF8 )
AS
DECLARE VARIABLE cnt INTEGER; 
BEGIN 
 SELECT count(USER_ID) FROM USERS WHERE USERNAME = :iUSERNAME INTO :cnt; 
 IF (cnt = 0) THEN 
  INSERT INTO USERS (USERNAME) VALUES (:iUSERNAME); 
 FOR SELECT USER_ID , '1.0.4'
  FROM USERS 
  WHERE USERNAME = :iUSERNAME 
  INTO :oUSER_ID , :oVERSION
  DO SUSPEND; 
END^
SET TERM ; ^
GRANT EXECUTE
 ON PROCEDURE OPENDB TO  SYSDBA;
