
SET TERM ^ ;
ALTER PROCEDURE MESSAGE_FIND (
    iUSER_ID Integer,
    iUSERNAME Varchar(32) CHARACTER SET UTF8,
    iSEARCH Varchar(32) CHARACTER SET UTF8,
    iLIMIT Integer )
RETURNS (
    oUSERNAME Varchar(32) CHARACTER SET UTF8,
    oCONTENT Varchar(4096) CHARACTER SET UTF8,
    oDIRECTION Varchar(8) CHARACTER SET UTF8,
    oCREATED Timestamp )
AS
BEGIN 

FOR SELECT FIRST (:iLIMIT) USERNAME, CONTENT, DIRECTION, CREATED 
FROM MESSAGES 
WHERE LOWER(CONTENT) like LOWER(:iSEARCH) 
AND USERNAME  = :iUSERNAME 
AND USER_ID =  :iUSER_ID 
ORDER BY CREATED DESC 
INTO :oUSERNAME, :oCONTENT, :oDIRECTION , :oCREATED DO
  BEGIN
   SUSPEND;
  END

END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_FIND TO  SYSDBA;

SET TERM ^ ;
ALTER PROCEDURE OPENDB (
    iUSERNAME Varchar(32) CHARACTER SET UTF8 )
RETURNS (
    oUSER_ID Integer,
    oVERSION Varchar(32) CHARACTER SET UTF8 )
AS
DECLARE VARIABLE cnt INTEGER; 
BEGIN 
 SELECT count(USER_ID) FROM USERS WHERE USERNAME = :iUSERNAME INTO :cnt; 
 IF (cnt = 0) THEN 
  INSERT INTO USERS (USERNAME) VALUES (:iUSERNAME); 
 FOR SELECT USER_ID , '1.0.1'
  FROM USERS 
  WHERE USERNAME = :iUSERNAME 
  INTO :oUSER_ID , :oVERSION
  DO SUSPEND; 
END^
SET TERM ; ^
GRANT EXECUTE
 ON PROCEDURE OPENDB TO  SYSDBA;