//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remwave.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Remwave.Client.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chat history found..
        /// </summary>
        internal static string txtArchiveInfoNoHistoryFound {
            get {
                return ResourceManager.GetString("txtArchiveInfoNoHistoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conf.
        /// </summary>
        internal static string txtBtnConf {
            get {
                return ResourceManager.GetString("txtBtnConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1.
        /// </summary>
        internal static string txtBtnConfLine1 {
            get {
                return ResourceManager.GetString("txtBtnConfLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2.
        /// </summary>
        internal static string txtBtnConfLine2 {
            get {
                return ResourceManager.GetString("txtBtnConfLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 3.
        /// </summary>
        internal static string txtBtnConfLine3 {
            get {
                return ResourceManager.GetString("txtBtnConfLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 4.
        /// </summary>
        internal static string txtBtnConfLine4 {
            get {
                return ResourceManager.GetString("txtBtnConfLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtBtnDialPad0 {
            get {
                return ResourceManager.GetString("txtBtnDialPad0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtBtnDialPad1 {
            get {
                return ResourceManager.GetString("txtBtnDialPad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abc.
        /// </summary>
        internal static string txtBtnDialPad2 {
            get {
                return ResourceManager.GetString("txtBtnDialPad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to def.
        /// </summary>
        internal static string txtBtnDialPad3 {
            get {
                return ResourceManager.GetString("txtBtnDialPad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ghi.
        /// </summary>
        internal static string txtBtnDialPad4 {
            get {
                return ResourceManager.GetString("txtBtnDialPad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ijk.
        /// </summary>
        internal static string txtBtnDialPad5 {
            get {
                return ResourceManager.GetString("txtBtnDialPad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mno.
        /// </summary>
        internal static string txtBtnDialPad6 {
            get {
                return ResourceManager.GetString("txtBtnDialPad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pqrs.
        /// </summary>
        internal static string txtBtnDialPad7 {
            get {
                return ResourceManager.GetString("txtBtnDialPad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuv.
        /// </summary>
        internal static string txtBtnDialPad8 {
            get {
                return ResourceManager.GetString("txtBtnDialPad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wxyz.
        /// </summary>
        internal static string txtBtnDialPad9 {
            get {
                return ResourceManager.GetString("txtBtnDialPad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtBtnDialPadPound {
            get {
                return ResourceManager.GetString("txtBtnDialPadPound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string txtBtnHold {
            get {
                return ResourceManager.GetString("txtBtnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1.
        /// </summary>
        internal static string txtBtnHoldLine1 {
            get {
                return ResourceManager.GetString("txtBtnHoldLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2.
        /// </summary>
        internal static string txtBtnHoldLine2 {
            get {
                return ResourceManager.GetString("txtBtnHoldLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 3.
        /// </summary>
        internal static string txtBtnHoldLine3 {
            get {
                return ResourceManager.GetString("txtBtnHoldLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 4.
        /// </summary>
        internal static string txtBtnHoldLine4 {
            get {
                return ResourceManager.GetString("txtBtnHoldLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string txtBtnLogin {
            get {
                return ResourceManager.GetString("txtBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec.
        /// </summary>
        internal static string txtBtnRec {
            get {
                return ResourceManager.GetString("txtBtnRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #AB.
        /// </summary>
        internal static string txtBtnShow1AB {
            get {
                return ResourceManager.GetString("txtBtnShow1AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string txtBtnShowAll {
            get {
                return ResourceManager.GetString("txtBtnShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDE.
        /// </summary>
        internal static string txtBtnShowCDE {
            get {
                return ResourceManager.GetString("txtBtnShowCDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FGH.
        /// </summary>
        internal static string txtBtnShowFGH {
            get {
                return ResourceManager.GetString("txtBtnShowFGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IJK.
        /// </summary>
        internal static string txtBtnShowIJK {
            get {
                return ResourceManager.GetString("txtBtnShowIJK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMN.
        /// </summary>
        internal static string txtBtnShowLMN {
            get {
                return ResourceManager.GetString("txtBtnShowLMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPQ.
        /// </summary>
        internal static string txtBtnShowOPQ {
            get {
                return ResourceManager.GetString("txtBtnShowOPQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RST.
        /// </summary>
        internal static string txtBtnShowRST {
            get {
                return ResourceManager.GetString("txtBtnShowRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVW.
        /// </summary>
        internal static string txtBtnShowUVW {
            get {
                return ResourceManager.GetString("txtBtnShowUVW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XYZ.
        /// </summary>
        internal static string txtBtnShowXYZ {
            get {
                return ResourceManager.GetString("txtBtnShowXYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xfer.
        /// </summary>
        internal static string txtBtnXfer {
            get {
                return ResourceManager.GetString("txtBtnXfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string txtCFormBtnSave {
            get {
                return ResourceManager.GetString("txtCFormBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an ordinary phone book contact.
        /// </summary>
        internal static string txtCFormInfo {
            get {
                return ResourceManager.GetString("txtCFormInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a contact to your contacts with  phone numbers information..
        /// </summary>
        internal static string txtCFormInfoDesc {
            get {
                return ResourceManager.GetString("txtCFormInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Book.
        /// </summary>
        internal static string txtCFormTitle {
            get {
                return ResourceManager.GetString("txtCFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string txtCFormTitleAddress {
            get {
                return ResourceManager.GetString("txtCFormTitleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string txtCFormTitleAddressCity {
            get {
                return ResourceManager.GetString("txtCFormTitleAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string txtCFormTitleAddressCountry {
            get {
                return ResourceManager.GetString("txtCFormTitleAddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string txtCFormTitleAddressEmail {
            get {
                return ResourceManager.GetString("txtCFormTitleAddressEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string txtCFormTitleAddressState {
            get {
                return ResourceManager.GetString("txtCFormTitleAddressState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string txtCFormTitleAddressStreet {
            get {
                return ResourceManager.GetString("txtCFormTitleAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string txtCFormTitleAddressZipCode {
            get {
                return ResourceManager.GetString("txtCFormTitleAddressZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First :.
        /// </summary>
        internal static string txtCFormTitleFirstName {
            get {
                return ResourceManager.GetString("txtCFormTitleFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM Address.
        /// </summary>
        internal static string txtCFormTitleIMAddress {
            get {
                return ResourceManager.GetString("txtCFormTitleIMAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string txtCFormTitleIMGroup {
            get {
                return ResourceManager.GetString("txtCFormTitleIMGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM Network.
        /// </summary>
        internal static string txtCFormTitleIMNetwork {
            get {
                return ResourceManager.GetString("txtCFormTitleIMNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string txtCFormTitleIMUsername {
            get {
                return ResourceManager.GetString("txtCFormTitleIMUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last :.
        /// </summary>
        internal static string txtCFormTitleLastName {
            get {
                return ResourceManager.GetString("txtCFormTitleLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle :.
        /// </summary>
        internal static string txtCFormTitleMiddleName {
            get {
                return ResourceManager.GetString("txtCFormTitleMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name details.
        /// </summary>
        internal static string txtCFormTitleNameDetails {
            get {
                return ResourceManager.GetString("txtCFormTitleNameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string txtCFormTitlePhoneBusiness {
            get {
                return ResourceManager.GetString("txtCFormTitlePhoneBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string txtCFormTitlePhoneHome {
            get {
                return ResourceManager.GetString("txtCFormTitlePhoneHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string txtCFormTitlePhoneMobile {
            get {
                return ResourceManager.GetString("txtCFormTitlePhoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers.
        /// </summary>
        internal static string txtCFormTitlePhones {
            get {
                return ResourceManager.GetString("txtCFormTitlePhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoIP.
        /// </summary>
        internal static string txtCFormTitlePhoneVoIP {
            get {
                return ResourceManager.GetString("txtCFormTitlePhoneVoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string txtCFormTitlePicture {
            get {
                return ResourceManager.GetString("txtCFormTitlePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string txtCFormTitlePictureChange {
            get {
                return ResourceManager.GetString("txtCFormTitlePictureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string txtChatCMenuSearch {
            get {
                return ResourceManager.GetString("txtChatCMenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is available only between {0} users..
        /// </summary>
        internal static string txtChatFeatureOnlyHomeNetwork
        {
            get {
                return ResourceManager.GetString("txtChatFeatureOnlyHomeNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File transfer error.
        /// </summary>
        internal static string txtChatFileTransferFailed {
            get {
                return ResourceManager.GetString("txtChatFileTransferFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File transfer failed. Do you want to retry to get the file?.
        /// </summary>
        internal static string txtChatFileTransferFailedDesc {
            get {
                return ResourceManager.GetString("txtChatFileTransferFailedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        internal static string txtChatInfoCloseTab {
            get {
                return ResourceManager.GetString("txtChatInfoCloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can nudge again, in {0} second(s).
        /// </summary>
        internal static string txtChatInfoNudgeAgain {
            get {
                return ResourceManager.GetString("txtChatInfoNudgeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudge has been sent..
        /// </summary>
        internal static string txtChatInfoNudgeSent {
            get {
                return ResourceManager.GetString("txtChatInfoNudgeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string txtChatInfoSenderSystem {
            get {
                return ResourceManager.GetString("txtChatInfoSenderSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string txtChatInfoSenderUser {
            get {
                return ResourceManager.GetString("txtChatInfoSenderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User appears to be offline, messages will be delivered when user sign in..
        /// </summary>
        internal static string txtChatInfoUserOfflineMessage {
            get {
                return ResourceManager.GetString("txtChatInfoUserOfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Chat.
        /// </summary>
        internal static string txtChatTitle {
            get {
                return ResourceManager.GetString("txtChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Sessions.
        /// </summary>
        internal static string txtChatTitleControl {
            get {
                return ResourceManager.GetString("txtChatTitleControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file .
        /// </summary>
        internal static string txtChatTitleOpenFileDialog {
            get {
                return ResourceManager.GetString("txtChatTitleOpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        internal static string txtChatTitleSaveFileDialog {
            get {
                return ResourceManager.GetString("txtChatTitleSaveFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        internal static string txtCMenuAddContact {
            get {
                return ResourceManager.GetString("txtCMenuAddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Contacts ....
        /// </summary>
        internal static string txtCMenuAddtoContacts {
            get {
                return ResourceManager.GetString("txtCMenuAddtoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call ....
        /// </summary>
        internal static string txtCMenuCall {
            get {
                return ResourceManager.GetString("txtCMenuCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Computer....
        /// </summary>
        internal static string txtCMenuCallComputer {
            get {
                return ResourceManager.GetString("txtCMenuCallComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Home ....
        /// </summary>
        internal static string txtCMenuCallHome {
            get {
                return ResourceManager.GetString("txtCMenuCallHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Mobile ....
        /// </summary>
        internal static string txtCMenuCallMobile {
            get {
                return ResourceManager.GetString("txtCMenuCallMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Phone2Phone ....
        /// </summary>
        internal static string txtCMenuCallPhone2Phone {
            get {
                return ResourceManager.GetString("txtCMenuCallPhone2Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call VoIP ....
        /// </summary>
        internal static string txtCmenuCallVoIP {
            get {
                return ResourceManager.GetString("txtCmenuCallVoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Work ....
        /// </summary>
        internal static string txtCMenuCallWork {
            get {
                return ResourceManager.GetString("txtCMenuCallWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Instant Message.
        /// </summary>
        internal static string txtCMenuChat {
            get {
                return ResourceManager.GetString("txtCMenuChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string txtCMenuContacts {
            get {
                return ResourceManager.GetString("txtCMenuContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string txtCMenuDelete {
            get {
                return ResourceManager.GetString("txtCMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ 0.00.
        /// </summary>
        internal static string txtCMenuPrepaidAmount {
            get {
                return ResourceManager.GetString("txtCMenuPrepaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update prepaid status.
        /// </summary>
        internal static string txtCMenuPrepaidAmountRefresh {
            get {
                return ResourceManager.GetString("txtCMenuPrepaidAmountRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Screen Sharing.
        /// </summary>
        internal static string txtCMenuScreenSharing {
            get {
                return ResourceManager.GetString("txtCMenuScreenSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Users.
        /// </summary>
        internal static string txtCMenuSearchforUsers {
            get {
                return ResourceManager.GetString("txtCMenuSearchforUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string txtCMenuSendEmail {
            get {
                return ResourceManager.GetString("txtCMenuSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message....
        /// </summary>
        internal static string txtCMenuSendMessage {
            get {
                return ResourceManager.GetString("txtCMenuSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Video Call ....
        /// </summary>
        internal static string txtCMenuStartVideoCall {
            get {
                return ResourceManager.GetString("txtCMenuStartVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Call.
        /// </summary>
        internal static string txtCMenuVideoCall {
            get {
                return ResourceManager.GetString("txtCMenuVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contact Properties.
        /// </summary>
        internal static string txtCMenuViewContactProperties {
            get {
                return ResourceManager.GetString("txtCMenuViewContactProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm before closing.
        /// </summary>
        internal static string txtConfirmBeforeClosing {
            get {
                return ResourceManager.GetString("txtConfirmBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string txtContact {
            get {
                return ResourceManager.GetString("txtContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string txtCSearchBtnAddUser {
            get {
                return ResourceManager.GetString("txtCSearchBtnAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Users.
        /// </summary>
        internal static string txtCSearchInfo {
            get {
                return ResourceManager.GetString("txtCSearchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you know your friend nick, e-mail or full name enter it in the box below..
        /// </summary>
        internal static string txtCSearchInfoDesc {
            get {
                return ResourceManager.GetString("txtCSearchInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtCSearchInfoGenderFemale {
            get {
                return ResourceManager.GetString("txtCSearchInfoGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string txtCSearchInfoGenderMale {
            get {
                return ResourceManager.GetString("txtCSearchInfoGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not specified.
        /// </summary>
        internal static string txtCSearchInfoGenderNA {
            get {
                return ResourceManager.GetString("txtCSearchInfoGenderNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching ....
        /// </summary>
        internal static string txtCSearchInfoSearching {
            get {
                return ResourceManager.GetString("txtCSearchInfoSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Search.
        /// </summary>
        internal static string txtCSearchTilte {
            get {
                return ResourceManager.GetString("txtCSearchTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age range.
        /// </summary>
        internal static string txtCSearchTitleAgeRange {
            get {
                return ResourceManager.GetString("txtCSearchTitleAgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtCSearchTitleCity {
            get {
                return ResourceManager.GetString("txtCSearchTitleCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string txtCSearchTitleComment {
            get {
                return ResourceManager.GetString("txtCSearchTitleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string txtCSearchTitleCompany {
            get {
                return ResourceManager.GetString("txtCSearchTitleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string txtCSearchTitleCountry {
            get {
                return ResourceManager.GetString("txtCSearchTitleCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string txtCSearchTitleFind {
            get {
                return ResourceManager.GetString("txtCSearchTitleFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string txtCSearchTitleFirstName {
            get {
                return ResourceManager.GetString("txtCSearchTitleFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string txtCSearchTitleLanguage {
            get {
                return ResourceManager.GetString("txtCSearchTitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string txtCSearchTitleLastName {
            get {
                return ResourceManager.GetString("txtCSearchTitleLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string txtCSearchTitleRegion {
            get {
                return ResourceManager.GetString("txtCSearchTitleRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtCSearchTitleState {
            get {
                return ResourceManager.GetString("txtCSearchTitleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string txtCSearchTitleUsername {
            get {
                return ResourceManager.GetString("txtCSearchTitleUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string txtIMAccountBtnDelete {
            get {
                return ResourceManager.GetString("txtIMAccountBtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string txtIMAccountBtnSave {
            get {
                return ResourceManager.GetString("txtIMAccountBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM Account.
        /// </summary>
        internal static string txtIMAccountTitle {
            get {
                return ResourceManager.GetString("txtIMAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string txtIMAccountTitleNetwork {
            get {
                return ResourceManager.GetString("txtIMAccountTitleNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string txtIMAccountTitlePassword {
            get {
                return ResourceManager.GetString("txtIMAccountTitlePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        internal static string txtIMAccountTitleUsername {
            get {
                return ResourceManager.GetString("txtIMAccountTitleUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM.
        /// </summary>
        internal static string txtIMAIM {
            get {
                return ResourceManager.GetString("txtIMAIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string txtInfoAbout {
            get {
                return ResourceManager.GetString("txtInfoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      Free your inner voice !
        ///      
        ///      ver. 2.0
        ///      .
        /// </summary>
        internal static string txtInfoAboutDesc {
            get {
                return ResourceManager.GetString("txtInfoAboutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage contact.
        /// </summary>
        internal static string txtInfoAddToContact {
            get {
                return ResourceManager.GetString("txtInfoAddToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add {0} to your own contact list.
        /// </summary>
        internal static string txtInfoAddToContactDesc {
            get {
                return ResourceManager.GetString("txtInfoAddToContactDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Closing.
        /// </summary>
        internal static string txtInfoApplicationClosing {
            get {
                return ResourceManager.GetString("txtInfoApplicationClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application..
        /// </summary>
        internal static string txtInfoApplicationClosingDesc {
            get {
                return ResourceManager.GetString("txtInfoApplicationClosingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Duration.
        /// </summary>
        internal static string txtInfoCallDuration {
            get {
                return ResourceManager.GetString("txtInfoCallDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling.
        /// </summary>
        internal static string txtInfoCalling {
            get {
                return ResourceManager.GetString("txtInfoCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234567890.
        /// </summary>
        internal static string txtInfoCallingValue {
            get {
                return ResourceManager.GetString("txtInfoCallingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} send you a file : {1}.
        /// </summary>
        internal static string txtInfoIMFileTransfer {
            get {
                return ResourceManager.GetString("txtInfoIMFileTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} accepted file transfer.
        /// </summary>
        internal static string txtInfoIMFileTransferAccepted {
            get {
                return ResourceManager.GetString("txtInfoIMFileTransferAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}  denied file transfer.
        /// </summary>
        internal static string txtInfoIMFileTransferDenied {
            get {
                return ResourceManager.GetString("txtInfoIMFileTransferDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file {0} filename....
        /// </summary>
        internal static string txtInfoIMFileTransferDownloading {
            get {
                return ResourceManager.GetString("txtInfoIMFileTransferDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of {1} to user {0} has been initialized..
        /// </summary>
        internal static string txtInfoIMFileTransferInitialized {
            get {
                return ResourceManager.GetString("txtInfoIMFileTransferInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer.
        /// </summary>
        internal static string txtInfoIMFileTransferInvitation {
            get {
                return ResourceManager.GetString("txtInfoIMFileTransferInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending message..
        /// </summary>
        internal static string txtInfoIMMessageSendError {
            get {
                return ResourceManager.GetString("txtInfoIMMessageSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending message: {0}.
        /// </summary>
        internal static string txtInfoIMMessageSendErrorDesc {
            get {
                return ResourceManager.GetString("txtInfoIMMessageSendErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string txtInfoIMNotification {
            get {
                return ResourceManager.GetString("txtInfoIMNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} send you a nudge.
        /// </summary>
        internal static string txtInfoIMSendYouNudge {
            get {
                return ResourceManager.GetString("txtInfoIMSendYouNudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Request.
        /// </summary>
        internal static string txtInfoIMSubcriptionRequest {
            get {
                return ResourceManager.GetString("txtInfoIMSubcriptionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} would like to add you to his/her contact list.  Do you wish to accept?.
        /// </summary>
        internal static string txtInfoIMSubcriptionRequestDesc {
            get {
                return ResourceManager.GetString("txtInfoIMSubcriptionRequestDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} accepted your invitation for video call.
        /// </summary>
        internal static string txtInfoIMVideoCallAccepted {
            get {
                return ResourceManager.GetString("txtInfoIMVideoCallAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} denied your invitation for video call.
        /// </summary>
        internal static string txtInfoIMVideoCallDenied {
            get {
                return ResourceManager.GetString("txtInfoIMVideoCallDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Call unvitation to {0} has been sent
        /// </summary>
        internal static string txtInfoIMVideoCallInvitationSent {
            get {
                return ResourceManager.GetString("txtInfoIMVideoCallInvitationSent", resourceCulture);
            }
        }
               
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} invites you for video call.
        /// </summary>
        internal static string txtInfoIMVideoCallInvitationRecived {
            get {
                return ResourceManager.GetString("txtInfoIMVideoCallInvitationRecived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Call.
        /// </summary>
        internal static string txtInfoIncomingCall {
            get {
                return ResourceManager.GetString("txtInfoIncomingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a call from : {0}.
        /// </summary>
        internal static string txtInfoIncomingCallDesc {
            get {
                return ResourceManager.GetString("txtInfoIncomingCallDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string txtInfoLineBusy {
            get {
                return ResourceManager.GetString("txtInfoLineBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call from :.
        /// </summary>
        internal static string txtInfoLineCallFrom {
            get {
                return ResourceManager.GetString("txtInfoLineCallFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling :.
        /// </summary>
        internal static string txtInfoLineCalling {
            get {
                return ResourceManager.GetString("txtInfoLineCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string txtInfoLineConnected {
            get {
                return ResourceManager.GetString("txtInfoLineConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialing....
        /// </summary>
        internal static string txtInfoLineDialing {
            get {
                return ResourceManager.GetString("txtInfoLineDialing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string txtInfoLineFree {
            get {
                return ResourceManager.GetString("txtInfoLineFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In call:.
        /// </summary>
        internal static string txtInfoLineInCall {
            get {
                return ResourceManager.GetString("txtInfoLineInCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Call ....
        /// </summary>
        internal static string txtInfoLineIncomingCall {
            get {
                return ResourceManager.GetString("txtInfoLineIncomingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string txtInfoLineReady {
            get {
                return ResourceManager.GetString("txtInfoLineReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version of {0} is  available for download!
        ///    Click [OK] to open the download page..
        /// </summary>
        internal static string txtInfoNewVersion {
            get {
                return ResourceManager.GetString("txtInfoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 2 Phone.
        /// </summary>
        internal static string txtInfoPhone2Phone {
            get {
                return ResourceManager.GetString("txtInfoPhone2Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start call - Payment Required : {0} to {1}.
        /// </summary>
        internal static string txtInfoPhone2PhonePaymentRequired {
            get {
                return ResourceManager.GetString("txtInfoPhone2PhonePaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying call  : {0} to {1}.
        /// </summary>
        internal static string txtInfoPhone2PhoneTrying {
            get {
                return ResourceManager.GetString("txtInfoPhone2PhoneTrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start call : {0} to {1}.
        /// </summary>
        internal static string txtInfoPhone2PhoneUnableToStartCall {
            get {
                return ResourceManager.GetString("txtInfoPhone2PhoneUnableToStartCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now {1} ({2}).
        /// </summary>
        internal static string txtInfoPresenceNotificationDesc {
            get {
                return ResourceManager.GetString("txtInfoPresenceNotificationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM - Connected.
        /// </summary>
        internal static string txtInfoServiceConnected {
            get {
                return ResourceManager.GetString("txtInfoServiceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are online!.
        /// </summary>
        internal static string txtInfoServiceConnectedDesc {
            get {
                return ResourceManager.GetString("txtInfoServiceConnectedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM - Service not reachable.
        /// </summary>
        internal static string txtInfoServiceNotReachable {
            get {
                return ResourceManager.GetString("txtInfoServiceNotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service does not respond, please check your network settings or try again later..
        /// </summary>
        internal static string txtInfoServiceNotReachableDesc {
            get {
                return ResourceManager.GetString("txtInfoServiceNotReachableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM - Network Unavailable.
        /// </summary>
        internal static string txtInfoServiceUnavailable {
            get {
                return ResourceManager.GetString("txtInfoServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} functionality will be limited, check your network..
        /// </summary>
        internal static string txtInfoServiceUnavailableDesc {
            get {
                return ResourceManager.GetString("txtInfoServiceUnavailableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio In Error.
        /// </summary>
        internal static string txtInfoSipEngineAudioInError {
            get {
                return ResourceManager.GetString("txtInfoSipEngineAudioInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize the audio capture subsystem..
        /// </summary>
        internal static string txtInfoSipEngineAudioInErrorDesc {
            get {
                return ResourceManager.GetString("txtInfoSipEngineAudioInErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Out Error.
        /// </summary>
        internal static string txtInfoSipEngineAudioOutError {
            get {
                return ResourceManager.GetString("txtInfoSipEngineAudioOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize the audio playback subsystem..
        /// </summary>
        internal static string txtInfoSipEngineAudioOutErrorDesc {
            get {
                return ResourceManager.GetString("txtInfoSipEngineAudioOutErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization Error.
        /// </summary>
        internal static string txtInfoSipEngineGeneralError {
            get {
                return ResourceManager.GetString("txtInfoSipEngineGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not initialize sip phone engine - Error ({0}).
        /// </summary>
        internal static string txtInfoSipEngineGeneralErrorDesc {
            get {
                return ResourceManager.GetString("txtInfoSipEngineGeneralErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string txtInfoStatusLable {
            get {
                return ResourceManager.GetString("txtInfoStatusLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string txtInfoStatusValue {
            get {
                return ResourceManager.GetString("txtInfoStatusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remwave Unified Storage - Error.
        /// </summary>
        internal static string txtInfoStorageEngineError {
            get {
                return ResourceManager.GetString("txtInfoStorageEngineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remwave Unified Storage could not be accessed make sure you run only one instance of the client. 
        ///    
        ///    Do you want to create new storage file?.
        /// </summary>
        internal static string txtInfoStorageEngineErrorDesc {
            get {
                return ResourceManager.GetString("txtInfoStorageEngineErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available..
        /// </summary>
        internal static string txtInfoUpdateAvailable {
            get {
                return ResourceManager.GetString("txtInfoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Website.
        /// </summary>
        internal static string txtInfoWebsite {
            get {
                return ResourceManager.GetString("txtInfoWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open My {0} area in your browser?.
        /// </summary>
        internal static string txtInfoWebsiteDesc {
            get {
                return ResourceManager.GetString("txtInfoWebsiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Failed.
        /// </summary>
        internal static string txtInfoWrongUsernamePassword {
            get {
                return ResourceManager.GetString("txtInfoWrongUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username / Password invalid!
        ///    Make sure you have your username typed in all lowercase letters and that your password is typed correctly..
        /// </summary>
        internal static string txtInfoWrongUsernamePasswordDesc {
            get {
                return ResourceManager.GetString("txtInfoWrongUsernamePasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account ....
        /// </summary>
        internal static string txtLinkCreateAccount {
            get {
                return ResourceManager.GetString("txtLinkCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string txtLinkForgotPassword {
            get {
                return ResourceManager.GetString("txtLinkForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Automatically.
        /// </summary>
        internal static string txtLinkLoginAutomatically {
            get {
                return ResourceManager.GetString("txtLinkLoginAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string txtLinkPassword {
            get {
                return ResourceManager.GetString("txtLinkPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string txtLinkRememberMe {
            get {
                return ResourceManager.GetString("txtLinkRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name :.
        /// </summary>
        internal static string txtLinkUsername {
            get {
                return ResourceManager.GetString("txtLinkUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string txtMenu {
            get {
                return ResourceManager.GetString("txtMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string txtMenuAbout {
            get {
                return ResourceManager.GetString("txtMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string txtMenuExit {
            get {
                return ResourceManager.GetString("txtMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string txtMenuFile {
            get {
                return ResourceManager.GetString("txtMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string txtMenuHelp {
            get {
                return ResourceManager.GetString("txtMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadu Gadu.
        /// </summary>
        internal static string txtMenuIMGG {
            get {
                return ResourceManager.GetString("txtMenuIMGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICQ.
        /// </summary>
        internal static string txtMenuIMICQ {
            get {
                return ResourceManager.GetString("txtMenuIMICQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Network.
        /// </summary>
        internal static string txtMenuIMDefault {
            get {
                return ResourceManager.GetString("txtMenuIMDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN.
        /// </summary>
        internal static string txtMenuIMMSN {
            get {
                return ResourceManager.GetString("txtMenuIMMSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        internal static string txtMenuIMYahoo {
            get {
                return ResourceManager.GetString("txtMenuIMYahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Me.
        /// </summary>
        internal static string txtMenuMe {
            get {
                return ResourceManager.GetString("txtMenuMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message history.
        /// </summary>
        internal static string txtMenuMessageHistroy {
            get {
                return ResourceManager.GetString("txtMenuMessageHistroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string txtMenuSettings {
            get {
                return ResourceManager.GetString("txtMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string txtMenuSignOut {
            get {
                return ResourceManager.GetString("txtMenuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string txtOtherGroup {
            get {
                return ResourceManager.GetString("txtOtherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string txtRACBtnCall {
            get {
                return ResourceManager.GetString("txtRACBtnCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Phone to Phone call.
        /// </summary>
        internal static string txtRACInfo {
            get {
                return ResourceManager.GetString("txtRACInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2Phone.
        /// </summary>
        internal static string txtRACTitle {
            get {
                return ResourceManager.GetString("txtRACTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call ....
        /// </summary>
        internal static string txtRACTitleCallFrom {
            get {
                return ResourceManager.GetString("txtRACTitleCallFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and ....
        /// </summary>
        internal static string txtRACTitleCallTo {
            get {
                return ResourceManager.GetString("txtRACTitleCallTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string txtRACTitleEnd {
            get {
                return ResourceManager.GetString("txtRACTitleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string txtRACTitlePhoneFromName {
            get {
                return ResourceManager.GetString("txtRACTitlePhoneFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string txtRACTitlePhoneToName {
            get {
                return ResourceManager.GetString("txtRACTitlePhoneToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        internal static string txtSDInfoNoRecordsFound {
            get {
                return ResourceManager.GetString("txtSDInfoNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to your contacts..
        /// </summary>
        internal static string txtSDInfoNoRecordsFoundDesc {
            get {
                return ResourceManager.GetString("txtSDInfoNoRecordsFoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name or phone number.
        /// </summary>
        internal static string txtSDTitleSearchDefault {
            get {
                return ResourceManager.GetString("txtSDTitleSearchDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string txtSettingsApplyButton {
            get {
                return ResourceManager.GetString("txtSettingsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        internal static string txtSettingsBasicSettings {
            get {
                return ResourceManager.GetString("txtSettingsBasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string txtSettingsCancelButton {
            get {
                return ResourceManager.GetString("txtSettingsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use local computer storage.
        /// </summary>
        internal static string txtSettingsContactsLocalStore {
            get {
                return ResourceManager.GetString("txtSettingsContactsLocalStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Outlook contacts.
        /// </summary>
        internal static string txtSettingsContactsOutlookStore {
            get {
                return ResourceManager.GetString("txtSettingsContactsOutlookStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use remote server storage.
        /// </summary>
        internal static string txtSettingsContactsServerStore {
            get {
                return ResourceManager.GetString("txtSettingsContactsServerStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts stores.
        /// </summary>
        internal static string txtSettingsContactsStores {
            get {
                return ResourceManager.GetString("txtSettingsContactsStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Quality Agent reporting.
        /// </summary>
        internal static string txtSettingsEnableQAReporting {
            get {
                return ResourceManager.GetString("txtSettingsEnableQAReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string txtSettingsGeneralTab {
            get {
                return ResourceManager.GetString("txtSettingsGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string txtSettingsLanguage {
            get {
                return ResourceManager.GetString("txtSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch when Windows starts.
        /// </summary>
        internal static string txtSettingsLaunchWhenWindowsStarts {
            get {
                return ResourceManager.GetString("txtSettingsLaunchWhenWindowsStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string txtSettingsOKButton {
            get {
                return ResourceManager.GetString("txtSettingsOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Codecs.
        /// </summary>
        internal static string txtSettingsPhoneAudioCodecs {
            get {
                return ResourceManager.GetString("txtSettingsPhoneAudioCodecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Volume.
        /// </summary>
        internal static string txtSettingsPhoneAudioVolume {
            get {
                return ResourceManager.GetString("txtSettingsPhoneAudioVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available codecs:.
        /// </summary>
        internal static string txtSettingsPhoneAvailableCodecs {
            get {
                return ResourceManager.GetString("txtSettingsPhoneAvailableCodecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled codecs:.
        /// </summary>
        internal static string txtSettingsPhoneEnabledCodecs {
            get {
                return ResourceManager.GetString("txtSettingsPhoneEnabledCodecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SIP diagnostic logging.
        /// </summary>
        internal static string txtSettingsPhoneEnableSIPLogging {
            get {
                return ResourceManager.GetString("txtSettingsPhoneEnableSIPLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        internal static string txtSettingsPhoneMicrophoneVolume {
            get {
                return ResourceManager.GetString("txtSettingsPhoneMicrophoneVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Tone.
        /// </summary>
        internal static string txtSettingsPhoneRingTone {
            get {
                return ResourceManager.GetString("txtSettingsPhoneRingTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string txtSettingsPhoneRingToneCustom {
            get {
                return ResourceManager.GetString("txtSettingsPhoneRingToneCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string txtSettingsPhoneRingToneDefault {
            get {
                return ResourceManager.GetString("txtSettingsPhoneRingToneDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string txtSettingsPhoneRingToneSelect {
            get {
                return ResourceManager.GetString("txtSettingsPhoneRingToneSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker.
        /// </summary>
        internal static string txtSettingsPhoneSpeakerVolume {
            get {
                return ResourceManager.GetString("txtSettingsPhoneSpeakerVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string txtSettingsPhoneTab {
            get {
                return ResourceManager.GetString("txtSettingsPhoneTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        internal static string txtStatusAway {
            get {
                return ResourceManager.GetString("txtStatusAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Disturb.
        /// </summary>
        internal static string txtStatusDND {
            get {
                return ResourceManager.GetString("txtStatusDND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Away.
        /// </summary>
        internal static string txtStatusExtendedAway {
            get {
                return ResourceManager.GetString("txtStatusExtendedAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string txtStatusOffline {
            get {
                return ResourceManager.GetString("txtStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string txtStatusOnline {
            get {
                return ResourceManager.GetString("txtStatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1.
        /// </summary>
        internal static string txtTabLine0 {
            get {
                return ResourceManager.GetString("txtTabLine0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 2.
        /// </summary>
        internal static string txtTabLine1 {
            get {
                return ResourceManager.GetString("txtTabLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 3.
        /// </summary>
        internal static string txtTabLine2 {
            get {
                return ResourceManager.GetString("txtTabLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 4.
        /// </summary>
        internal static string txtTabLine3 {
            get {
                return ResourceManager.GetString("txtTabLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOL IM Network.
        /// </summary>
        internal static string txtTitleAIMNetwork {
            get {
                return ResourceManager.GetString("txtTitleAIMNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call History.
        /// </summary>
        internal static string txtTitleCallHistory {
            get {
                return ResourceManager.GetString("txtTitleCallHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial Pad.
        /// </summary>
        internal static string txtTitleDialPad {
            get {
                return ResourceManager.GetString("txtTitleDialPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string txtTitleDialPadTabPage {
            get {
                return ResourceManager.GetString("txtTitleDialPadTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadu Gadu Network.
        /// </summary>
        internal static string txtTitleGGNetwork {
            get {
                return ResourceManager.GetString("txtTitleGGNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICQ Netwrok.
        /// </summary>
        internal static string txtTitleICQNetwork {
            get {
                return ResourceManager.GetString("txtTitleICQNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC Network.
        /// </summary>
        internal static string txtTitleIRCNetwork {
            get {
                return ResourceManager.GetString("txtTitleIRCNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string txtTitleLines {
            get {
                return ResourceManager.GetString("txtTitleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string txtTitleMainContactsTabPage {
            get {
                return ResourceManager.GetString("txtTitleMainContactsTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my Account.
        /// </summary>
        internal static string txtTitleMainMyAccountTabPage {
            get {
                return ResourceManager.GetString("txtTitleMainMyAccountTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txtTitleMainTabControl {
            get {
                return ResourceManager.GetString("txtTitleMainTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string txtTitleMainTabOnlinePage {
            get {
                return ResourceManager.GetString("txtTitleMainTabOnlinePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN Network.
        /// </summary>
        internal static string txtTitleMSNNetwork {
            get {
                return ResourceManager.GetString("txtTitleMSNNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string txtTitleNotifyIcon {
            get {
                return ResourceManager.GetString("txtTitleNotifyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string txtTitleStatus {
            get {
                return ResourceManager.GetString("txtTitleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string txtTitleStoreLocal {
            get {
                return ResourceManager.GetString("txtTitleStoreLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook.
        /// </summary>
        internal static string txtTitleStoreOutlook {
            get {
                return ResourceManager.GetString("txtTitleStoreOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string txtTitleStoreServer {
            get {
                return ResourceManager.GetString("txtTitleStoreServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Mail.
        /// </summary>
        internal static string txtTitleVoiceMail {
            get {
                return ResourceManager.GetString("txtTitleVoiceMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo Network.
        /// </summary>
        internal static string txtTitleYahooNetwork {
            get {
                return ResourceManager.GetString("txtTitleYahooNetwork", resourceCulture);
            }
        }
    }
}
