
/******************* PROCEDURES ******************/

SET TERM ^ ;
CREATE PROCEDURE MESSAGE_FIND_BY_DATE (
    iUSER_ID Integer,
    iJID Varchar(64) CHARACTER SET UTF8,
    iSEARCH Varchar(64) CHARACTER SET UTF8,
    iLIMIT Integer,
iDATE Date	)
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
ALTER PROCEDURE MESSAGE_FIND_BY_DATE (
    iUSER_ID Integer,
    iJID Varchar(64) CHARACTER SET UTF8,
    iSEARCH Varchar(64) CHARACTER SET UTF8,
    iLIMIT Integer,
iDATE Date	)
RETURNS (
    oJID Varchar(64) CHARACTER SET UTF8,
	oCONTENT_TEXT Varchar(4096) CHARACTER SET UTF8,
    oCONTENT_HTML Varchar(6144) CHARACTER SET UTF8,
    oDIRECTION Varchar(8) CHARACTER SET UTF8,
    oCREATED Timestamp )
AS
BEGIN 

FOR SELECT FIRST (:iLIMIT) JID, CONTENT_TEXT, CONTENT_HTML, DIRECTION, CREATED 
FROM MESSAGES 
WHERE LOWER(CONTENT_TEXT) like LOWER(:iSEARCH) 
AND JID = LOWER(:iJID)
AND USER_ID =  :iUSER_ID 
AND USER_ID =  :iUSER_ID
AND  CAST (CREATED AS DATE)  = :iDATE 
ORDER BY CREATED DESC 
INTO :oJID, :oCONTENT_TEXT,oCONTENT_HTML, :oDIRECTION , :oCREATED DO
  BEGIN
   SUSPEND;
  END

END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_FIND_BY_DATE TO  SYSDBA;

SET TERM ^ ;
CREATE PROCEDURE MESSAGE_DATES_FIND (
    iUSER_ID Integer,
    iJID Varchar(64) CHARACTER SET UTF8,
    iSEARCH Varchar(64) CHARACTER SET UTF8,
    iLIMIT Integer )
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
ALTER PROCEDURE MESSAGE_DATES_FIND (
    iUSER_ID Integer,
    iJID Varchar(64) CHARACTER SET UTF8,
    iSEARCH Varchar(64) CHARACTER SET UTF8,
    iLIMIT Integer )
RETURNS (
    oDAY Date,
	oDATE Timestamp,
	oDAYS Integer)
AS
BEGIN 

FOR SELECT FIRST (:iLIMIT)  MAX(CREATED) DATE_, CAST (CREATED AS DATE)  DAY_,  CAST ('NOW' AS DATE) - CAST (CREATED AS DATE) DAYS_
FROM MESSAGES 
WHERE LOWER(CONTENT_TEXT) like LOWER(:iSEARCH) 
AND JID = LOWER(:iJID)
AND USER_ID =  :iUSER_ID 
GROUP by CAST (CREATED AS DATE) , CAST ('NOW' AS DATE) -  CAST (CREATED AS DATE)
ORDER by DAY_ DESC
INTO :oDATE, :oDAY, :oDAYS DO
  BEGIN
   SUSPEND;
  END

END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE MESSAGE_DATES_FIND TO  SYSDBA;

 
 

SET TERM ^ ;
ALTER PROCEDURE OPENDB (
    iUSERNAME Varchar(64) CHARACTER SET UTF8 )
RETURNS (
    oUSER_ID Integer,
    oVERSION Varchar(32) CHARACTER SET UTF8 )
AS
DECLARE VARIABLE cnt INTEGER; 
BEGIN 
 SELECT count(USER_ID) FROM USERS WHERE USERNAME = :iUSERNAME INTO :cnt; 
 IF (cnt = 0) THEN 
  INSERT INTO USERS (USERNAME) VALUES (:iUSERNAME); 
 FOR SELECT USER_ID , '1.0.5'
  FROM USERS 
  WHERE USERNAME = :iUSERNAME 
  INTO :oUSER_ID , :oVERSION
  DO SUSPEND; 
END^
SET TERM ; ^
GRANT EXECUTE
 ON PROCEDURE OPENDB TO  SYSDBA;
